// Single source of truth for all sport/position/drill data used across the app.

export type DrillTemplate = {
  title: string;
  duration: string;
  category: 'Position Specific' | 'Conditioning' | 'IQ & Strategy' | 'Strength' | 'Skills';
  intel: string;
};

export type SportConfig = {
  positions: string[];
  abilities: string[];
  improvements: string[];
  drills: DrillTemplate[];
  aiContext: string;
};

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  Soccer: {
    positions: ['Goalkeeper', 'Centre-Back', 'Full-Back', 'Wing-Back', 'Defensive Mid', 'Central Mid', 'Attacking Mid', 'Winger', 'Striker'],
    abilities: ['Stamina', 'Dribbling', 'Passing', 'Tackling', 'Finishing', 'Pace'],
    improvements: ['Tactical Sense', 'Crosses', 'Weak Foot', 'Heading', 'Set Pieces', 'Positioning'],
    drills: [
      { title: 'Cone Dribbling Course', duration: '12 min', category: 'Skills', intel: '1. Set 8 cones 1m apart in a zigzag line.\n2. Dribble through at 70% pace, both feet, keeping the ball under 30cm from your foot.\n3. Sprint through the final gate at full pace.\n4. 4 sets — rest 45s between each.' },
      { title: 'Wall Passing — One-Two Combos', duration: '10 min', category: 'Skills', intel: '1. Stand 3m from a solid wall.\n2. Pass firmly with the inside of your foot, control the return, pass again.\n3. Vary: right foot only, left foot only, alternate.\n4. Target 80 clean touches in 10 minutes.' },
      { title: 'Rondo / Possession Circle', duration: '15 min', category: 'IQ & Strategy', intel: '1. If you have teammates: 4v1 in a 6m circle — the defender pressures, others keep possession.\n2. Solo: pass against the wall, receive, pivot, pass again — no more than 2 touches.\n3. Focus on quick decision-making under pressure.' },
      { title: 'Finishing — Low Drives', duration: '12 min', category: 'Position Specific', intel: '1. Place ball 18m from goal (or a target on a wall).\n2. Drive through the ball with your laces — keep it below knee height.\n3. Aim corners: bottom-left, bottom-right.\n4. 5 shots each side, 2 rounds.' },
      { title: 'Box-to-Box Runs', duration: '15 min', category: 'Conditioning', intel: '1. Sprint from one 18-yard box to the other (or mark 50m).\n2. Walk/jog back — this is your recovery.\n3. 10 reps. If your 10th is slower than your 1st by more than 3 seconds, stop there.\n4. Builds specific soccer stamina.' },
      { title: '1v1 Defensive Shape', duration: '10 min', category: 'Position Specific', intel: '1. Mark a 5m channel.\n2. Have someone dribble at you (or imagine an attacker).\n3. Stay on the balls of your feet, side-on, deny the inside pass.\n4. Delay for 3 seconds before attempting a tackle — practice patience.' },
      { title: 'First Touch Control', duration: '10 min', category: 'Skills', intel: '1. Throw the ball in the air or kick against a wall.\n2. On every return, take ONE controlling touch — set for your next action.\n3. Alternate: inside of foot, outside, thigh, chest.\n4. The touch must land within 50cm of your body.' },
      { title: 'Set Piece Delivery', duration: '12 min', category: 'IQ & Strategy', intel: '1. Place ball on corner spot or edge of box.\n2. Pick a target zone: near post, far post, penalty spot.\n3. Strike with the inside of your foot, generating whip/curve.\n4. 10 deliveries per zone — track how many land on target.' },
      { title: 'Agility Ladder — Soccer Patterns', duration: '10 min', category: 'Conditioning', intel: '1. Run 3 patterns: single-foot each rung, lateral in-out, two-feet-forward.\n2. 4 runs per pattern at full speed.\n3. Rest 30s between runs.\n4. Improves foot speed for quick directional changes.' },
      { title: 'Goalkeeper Distribution Drill', duration: '12 min', category: 'Position Specific', intel: '1. Take goal kicks to two targets: right channel and left channel (marked with cones at 40m).\n2. 10 goal kicks, 10 short rollouts to a teammate (or cone).\n3. For rollouts: get low, use underarm motion, keep it along the ground.' },
      { title: 'High Press Trigger', duration: '10 min', category: 'IQ & Strategy', intel: '1. Visualize the opponent\'s CB receiving the ball.\n2. On the "trigger" (poor touch, back pass), sprint 10m at full pace to close down.\n3. Set up 6 sprint triggers from rest — simulate match-intensity pressing.\n4. Recover slowly between each.' },
      { title: 'Crossing Delivery — Wide Play', duration: '12 min', category: 'Skills', intel: '1. Start at the corner flag or wide channel.\n2. Dribble 5m infield, then whip a cross to far post, near post, and cutback zones.\n3. Use the inside of your foot for accuracy, laces for power.\n4. 5 crosses each zone per side.' },
    ],
    aiContext: 'Soccer: 90-minute match (two 45-min halves). High aerobic demand — midfielders cover 10–13km per game. Position-specific loads vary (strikers: sprint-heavy; defenders: reactive; midfielders: continuous). Training should prioritize repeated sprint ability, ball control, and positional awareness. Avoid leg fatigue within 48h of a match.',
  },

  Basketball: {
    positions: ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'],
    abilities: ['Speed', 'Shooting', 'Passing', 'Defense', 'Basketball IQ', 'Agility'],
    improvements: ['Ball Handling', 'Rebounding', 'Free Throws', 'Post-Up', 'Endurance', 'Footwork'],
    drills: [
      { title: 'Mikan Drill', duration: '8 min', category: 'Skills', intel: '1. Stand under the basket.\n2. Lay up with right hand off right foot, catch, lay up left hand off left foot — alternate continuously.\n3. Stay close to the glass — this is a finishing drill, not a dribbling one.\n4. 60 makes as fast as possible.' },
      { title: 'Ball Handling Series', duration: '10 min', category: 'Skills', intel: '1. Stationary: crossover, between-legs, behind-back — 30 reps each.\n2. Add movement: attack left, attack right, hesitation step, spin.\n3. Keep eyes up — never look at the ball.\n4. Speed ramp: slow, medium, fast over 3 sets.' },
      { title: 'Defensive Slide + Closeout', duration: '10 min', category: 'Conditioning', intel: '1. Start at the paint. Slide laterally to the 3-point corner (6m), back to the opposite corner.\n2. On the coach\'s call (or every 10 slides), sprint out to close out — hands high, chop feet.\n3. 5 sets of 3 slides + closeout.' },
      { title: 'Catch & Shoot — Off Screen Read', duration: '12 min', category: 'Position Specific', intel: '1. Set up a chair or cone as a "screen" above the key.\n2. Walk into the screen, curl or fade depending on the imaginary defender.\n3. Catch (self-pass against wall or have someone feed) and shoot in one motion.\n4. 10 curl shots, 10 fade shots each side.' },
      { title: 'Free Throw Mental Routine', duration: '8 min', category: 'Skills', intel: '1. Step to the line. Bounce the ball exactly 3 times.\n2. Take one deep breath. Visualize the ball going through the net.\n3. Shoot with a consistent arc — aim 10cm above the back of the rim.\n4. 25 free throws. Track makes. Target 80% or above.' },
      { title: 'Three-Man Weave Pattern', duration: '10 min', category: 'IQ & Strategy', intel: '1. Solo version: sprint 5 meters, jump stop, pivot, pass to the wall.\n2. Follow your pass — run to where the ball will return.\n3. Simulate a teammate fill with the rebound.\n4. Builds pass-and-cut spacing intuition even without teammates.' },
      { title: 'Pick & Roll Read', duration: '12 min', category: 'IQ & Strategy', intel: '1. Dribble to the elbow. Imagine a big setting a screen.\n2. Read: if "defender goes under" → pull up mid-range. If "defender goes over" → attack downhill. If "hedge" → hit the roller (pass to imaginary cutter).\n3. 10 reps of each read. Execute the correct shot or drive.' },
      { title: 'Post-Up Footwork — Drop Step & Hook', duration: '12 min', category: 'Position Specific', intel: '1. Receive the ball on the block (low post).\n2. Drop step: drop foot toward the baseline, spin, and power lay-up.\n3. Hook shot: same position, face baseline, use the near hand to hook over the imaginary defender.\n4. 10 drop steps each side, 10 hooks each side.' },
      { title: 'Reactive Agility Ladder', duration: '10 min', category: 'Conditioning', intel: '1. Lay out a 5m agility ladder (or mark with tape).\n2. Run 4 patterns: 1-foot per rung, lateral shuffle, in-in-out-out, hopscotch.\n3. 4 runs per pattern. Rest 20s between each.\n4. Drive your arms — upper body powers ladder speed.' },
      { title: 'Drive & Kick Decision', duration: '12 min', category: 'IQ & Strategy', intel: '1. Start at the top of the key with the ball.\n2. Drive hard at 3 o\'clock (right baseline). Before the help defender arrives, kick out to an imaginary corner shooter.\n3. Repeat: 9 o\'clock drive, kick to the opposite corner.\n4. 10 drives each side — focus on the one-step lead pass.' },
      { title: 'Form Shooting — Range Builder', duration: '12 min', category: 'Skills', intel: '1. Start at the rim — shoot with one hand (strong arm only). 10 makes.\n2. Move back to the elbow. 10 makes.\n3. Move to the 3-point line. 10 makes.\n4. Only advance when you hit 8/10. This builds consistent mechanics at range.' },
      { title: 'Full-Court Sprint Recovery', duration: '10 min', category: 'Conditioning', intel: '1. Sprint end-to-end at 90% — simulate a fast break.\n2. Jog back.\n3. 8 reps. 90s rest at the halfway point.\n4. Conditions you to recover offensively after sprinting in transition.' },
    ],
    aiContext: 'Basketball: 4 x 12-minute quarters (FIBA) or 4 x 12min (NBL) / 4 x 12min (NBA). High-intensity interval sport — repeated sprints, jumps, lateral cuts. Guards need agility and endurance; bigs need strength and vertical. Training should balance explosive power work with skill repetition. Rest the legs 24h before game day.',
  },

  AFL: {
    positions: ['Full Forward', 'Half Forward Flank', 'Centre', 'Wing', 'Half Back Flank', 'Full Back', 'Ruckman', 'Ruck-Rover', 'Utility'],
    abilities: ['Endurance', 'Marking', 'Kicking', 'Handballing', 'Speed', 'Contested Ball'],
    improvements: ['Set Shot Accuracy', 'Leading Patterns', 'Defensive Pressure', 'Clearances', 'Aerial Marking', 'Decision Speed'],
    drills: [
      { title: 'Drop Punt Form Drill', duration: '12 min', category: 'Skills', intel: '1. Hold the ball in two hands, point the seam down the middle.\n2. Drop the ball — don\'t throw it — letting it fall vertically.\n3. Strike through the ball with your laces at the contact point, follow through straight.\n4. Start 15m away from a target, move back 5m each time you hit 5 in a row.' },
      { title: 'Overhead Marking — Two Hands', duration: '10 min', category: 'Skills', intel: '1. Have a partner kick (or use a wall rebound): high ball, 10m away.\n2. Attack the ball — don\'t wait for it. Plant your leading foot, jump off two feet or one.\n3. Hands form a "W" shape — thumbs together, fingers spread behind the ball.\n4. 15 marks each side.' },
      { title: 'Handball Exchange Series', duration: '10 min', category: 'Skills', intel: '1. Ball in one hand, punch with the closed fist of the other.\n2. Stationary: 10 handballs right, 10 left — hit an exact target (chalk mark on wall).\n3. Moving: run forward, handball, sprint to retrieve, handball back.\n4. Keep the ball firm — don\'t drop the fist through.' },
      { title: 'Leading Run Patterns', duration: '12 min', category: 'Position Specific', intel: '1. From a standing start, sprint toward an imaginary ball carrier.\n2. Change direction at the 10m mark (lead change) — cut hard back across.\n3. Signal for the ball at the point of the lead.\n4. 10 straight leads, 10 lead changes. Rest 30s between.' },
      { title: 'Set Shot Routine', duration: '12 min', category: 'Skills', intel: '1. Place ball 20m out, central. Go through your pre-kick routine: same steps every time.\n2. Pick a spot 10m behind the goals to aim at. Look up, look down, kick.\n3. Move to the 30-degree angle left, then right.\n4. 5 shots each position. Track score out of 15.' },
      { title: 'Chase Down & Tackle Pressure', duration: '10 min', category: 'Conditioning', intel: '1. Sprint 15m at full pace to "catch" a lead runner (imagined or a cone).\n2. Practice the tackle wrap: arms around the body, drive through, pull to ground.\n3. 6 chase-down + wrap reps. 45s rest between each.\n4. Focus on tracking the ball carrier\'s hips, not feet.' },
      { title: 'Ruck Tap Technique', duration: '10 min', category: 'Position Specific', intel: '1. Jump as high as possible — both feet.\n2. At peak height, use flat palm or fingertips to tap the ball forward (6 o\'clock to 12 o\'clock).\n3. Practice 10 taps to the left, 10 to the right.\n4. Focus: eyes on the ball, arm fully extended, direct the tap not slap.' },
      { title: 'Boundary Throw-In Rotation', duration: '10 min', category: 'IQ & Strategy', intel: '1. Study the boundary throw-in scenario: ball goes out on the wing.\n2. As a rover or midfielder, visualize: position yourself 2m from the contest.\n3. If the ruckman taps forward, drive into open space. If the tap goes back, switch sides.\n4. Walk through 6 scenarios, then sprint through 6.' },
      { title: 'Kick-to-Kick Distance Builder', duration: '15 min', category: 'Skills', intel: '1. Start 20m from a partner (or target).\n2. Kick accurately. If both players catch or hit target, move back 5m.\n3. Continue until maximum accurate range is reached.\n4. Solo version: kick at a target, walk, repeat at increasing distances.' },
      { title: 'Contested Ball Endurance', duration: '12 min', category: 'Conditioning', intel: '1. Lay the ball on the ground. Sprint 10m to the ball, pick it up, handball to a target.\n2. Sprint back to start.\n3. 10 reps — your body must still be working hard at rep 10.\n4. Simulates the contested efforts a midfielder makes in each quarter.' },
      { title: 'Zone Defensive Awareness', duration: '10 min', category: 'IQ & Strategy', intel: '1. Visualize your zone on the back half of the ground.\n2. Walk through: where is your zonal responsibility when the ball is on each side?\n3. Mark on the ground with cones. Sprint to your zone position on each scenario.\n4. Builds automatic defensive positioning instinct.' },
      { title: 'Speed Endurance — 150m Repeats', duration: '15 min', category: 'Conditioning', intel: '1. Sprint 150m at 85-90% effort.\n2. Walk back (90s recovery).\n3. 6 repeats.\n4. This mimics the run-rest-run pattern of AFL quarter efforts.' },
    ],
    aiContext: 'AFL (Australian Rules Football): 4 x 20-minute quarters (plus time on). Highest aerobic demand of any team sport — elite players average 12–14km per game. Involves explosive bursts, contested aerial duels, and continuous running. Positions range from pure endurance (midfielders, wings) to strength/power (ruckmen, key forwards/backs). Training should heavily emphasize repeat sprint ability, contested ball skills, and kicking technique. Game day nutrition: carb-load the day before; light and easy morning of.',
  },

  'Rugby League': {
    positions: ['Prop', 'Hooker', 'Second Row', 'Lock', 'Halfback', 'Five-Eighth', 'Centre', 'Wing', 'Fullback'],
    abilities: ['Strength', 'Speed', 'Tackling', 'Ball Carrying', 'Communication', 'Endurance'],
    improvements: ['Offloading', 'Dummy Half Play', 'Defensive Line Speed', 'Kicking Game', 'Edge Defence', 'Short Ball'],
    drills: [
      { title: 'Tackle Technique — Bag Work', duration: '12 min', category: 'Skills', intel: '1. Approach the tackle bag at 70% speed.\n2. Drive your cheek to the ball carrier\'s thigh — head to the side.\n3. Wrap both arms, drive through with your legs.\n4. 3 sets of 5 tackle attempts. Focus: head position every rep.' },
      { title: 'Offload in Contact', duration: '10 min', category: 'Skills', intel: '1. Run into a tackle bag or have a partner hold you.\n2. As contact is made, pop the ball out with a quick-arm offload — don\'t fully commit both arms to the carry.\n3. Practice left and right hand offloads.\n4. 5 reps each arm. The ball must be catchable.' },
      { title: 'Dummy Half — Speed Play', duration: '12 min', category: 'Position Specific', intel: '1. From a ruck (cone on ground), scoop the ball quickly.\n2. Sprint 5m left, 5m right (simulate dummy half darting run).\n3. Add a play-the-ball step: roll ball, pick up, immediate play.\n4. 10 reps left, 10 reps right. Speed is everything — get the ball away in 2 seconds.' },
      { title: 'Line Speed + Blitz Defense', duration: '10 min', category: 'IQ & Strategy', intel: '1. Stand 10m from a cone (acting as the ruck).\n2. On "play", sprint forward 3–4 steps to establish a flat defensive line.\n3. Hold your line — don\'t drift. Point your inside shoulder to the ball carrier.\n4. 8 reps, varying speed of "play" call.' },
      { title: 'Kick Chase & Pressure', duration: '12 min', category: 'Conditioning', intel: '1. Kick the ball high (bomb) or kick for touch.\n2. Sprint full pace to contest the kick — arrive within 2 seconds of the ball landing.\n3. 8 kick-chase reps. Track how close you arrive to the landing point.\n4. Work on maintaining pace at rep 7–8 (fatigue replication).' },
      { title: '2v1 Attack Drill', duration: '12 min', category: 'IQ & Strategy', intel: '1. Ball carrier + support player vs. 1 defender.\n2. The ball carrier must commit the defender before passing — don\'t pass early.\n3. If the defender holds the ball carrier, the offload/pass should free the support player.\n4. 10 reps. Swap roles every 5.' },
      { title: 'Ruck Speed — Body Position', duration: '10 min', category: 'Skills', intel: '1. Take contact with a bag, go to ground in a controlled way.\n2. Immediately place the ball back toward your teammates — don\'t hold it under your body.\n3. Jump back to your feet in under 2 seconds.\n4. 12 reps. The ball placement is the most important part.' },
      { title: 'Spiral Kick Technique', duration: '10 min', category: 'Skills', intel: '1. Hold the ball in two hands at a slight diagonal.\n2. Drop it to your foot — the ball should spiral in the air, not tumble.\n3. Follow through down the line of the target, laces contact the mid-seam.\n4. 20 kicks, tracking spiral quality vs. wobbles.' },
      { title: 'Edge Defence — Drift Pattern', duration: '12 min', category: 'IQ & Strategy', intel: '1. Walk through the defensive line when the ball is wide.\n2. Outside defenders drift slightly — don\'t rush the ball carrier.\n3. Trigger: if the ball carrier steps in, hit him. If he throws wide, drift onto next receiver.\n4. Sprint through 6 drift + tackle scenarios.' },
      { title: 'Power Step — Pre-Contact', duration: '10 min', category: 'Conditioning', intel: '1. Sprint 10m at full pace. At a cone (5m from a bag), drop your hips and plant a power step.\n2. Drive through the bag with your legs — not your shoulders.\n3. 8 reps. The power step adds 10–15% force transfer before contact.' },
      { title: 'Repeat Sprint — Set Simulator', duration: '12 min', category: 'Conditioning', intel: '1. Sprint 40m (one set), walk back.\n2. Sprint 40m again — 6 in a row = one set of 6.\n3. Rest 60s, then another set.\n4. 3 total sets. Simulates back-to-back sets in a half.' },
      { title: 'Short Ball — Hit-Up Timing', duration: '10 min', category: 'Position Specific', intel: '1. Halfback or five-eighth role: run to a point, time the short pass to an arriving forward.\n2. The forward should receive the ball already moving at pace.\n3. The pass must be short, flat, and on target — not a lob.\n4. 10 reps each; swap ball carrier and receiver.' },
    ],
    aiContext: 'Rugby League (NRL): 80 minutes, two 40-minute halves. Each team gets 6 tackles per possession. High-contact sport with repeated explosive efforts — props and forwards make 20–30 carries and 30+ tackles per game. Halves and fullback have kicking duties. Speed and power are critical for backs; contact strength for forwards. Training must replicate repeated sprint + contact patterns. Heavy upper body work must be timed away from game day.',
  },

  'Rugby Union': {
    positions: ['Loosehead Prop', 'Hooker', 'Tighthead Prop', 'Lock', 'Blindside Flanker', 'Openside Flanker', 'Number 8', 'Scrum-Half', 'Fly-Half', 'Inside Centre', 'Outside Centre', 'Wing', 'Fullback'],
    abilities: ['Scrummaging', 'Lineout', 'Ball Carrying', 'Tackling', 'Kicking', 'Support Lines'],
    improvements: ['Breakdown Work', 'Offloading', 'Set Piece', 'Tactical Kicking', 'Defense Shape', 'Communication'],
    drills: [
      { title: 'Scrum Binding & Drive', duration: '12 min', category: 'Position Specific', intel: '1. Bind tightly to your prop (or simulate against a wall/bag).\n2. Head up, spine neutral — no neck tension.\n3. Drive with your legs, not your back. Push through the heels.\n4. 6 x 8-second drives against resistance. Rest 30s between.' },
      { title: 'Spiral Pass — Scrum-Half Mechanics', duration: '10 min', category: 'Skills', intel: '1. Ball on the ground (simulate a ruck). Pick up with two hands.\n2. Stand side-on, swing through to your fly-half target with fingertips dragging over the seam.\n3. Follow through pointing at target. The ball should spiral — not tumble.\n4. 20 passes each side, at varying distances (5m to 15m).' },
      { title: 'Tackle Height & Wrap', duration: '10 min', category: 'Skills', intel: '1. Target thigh height — below the hips, above the knees.\n2. Drive your cheek across the thigh, arms wrap, then drive with legs.\n3. Full wrap: don\'t just shirt-grab. Secure both arms before the drive.\n4. 5 bag tackles each side. Never lead with head.' },
      { title: 'Ruck Body Position', duration: '10 min', category: 'Skills', intel: '1. Approach the ruck at speed. Bind to a teammate\'s hips — not shoulders.\n2. Drive horizontally through the contact point with your legs.\n3. Head and spine aligned — don\'t dip.\n4. 10 ruck entries. Focus on footwork placement before binding.' },
      { title: 'Box Kick Technique', duration: '12 min', category: 'Position Specific', intel: '1. Scrum-Half role: ball at your feet, pick up, two steps, kick.\n2. Aim high and short — land just behind the defending back three.\n3. Target hang time over distance.\n4. 15 box kicks. Track your best hang-to-contestability ratio.' },
      { title: 'Offload Ball Security', duration: '10 min', category: 'Skills', intel: '1. Run into a bag (contact). As you\'re "tackled," secure the ball in two hands.\n2. Pop a short offload to the side before going to ground.\n3. Alternate: left and right side offload.\n4. 10 reps each side. If you can\'t secure in contact, hold — don\'t fumble.' },
      { title: 'Support Lines — Attack Pattern', duration: '12 min', category: 'IQ & Strategy', intel: '1. Ball carrier takes the ball to contact.\n2. First support: arrive close, present as the ruck cleaner.\n3. Second support: set your pipe (5m from ruck), ready to receive.\n4. Walk through this 4-player pattern 8 times, then jog through 4 times.' },
      { title: 'Kick Chase — Choke Tackle', duration: '10 min', category: 'Conditioning', intel: '1. Kick a high ball, sprint to arrive as it lands.\n2. If the catcher catches cleanly, your target is a choke tackle: hold the arms, prevent the release.\n3. If the ball bounces, fly into the contest low.\n4. 8 chase reps. Rest 45s between each.' },
      { title: 'Lineout Jump & Lift', duration: '12 min', category: 'Position Specific', intel: '1. Jumper: explode off both feet, hands up to receive at peak.\n2. Lifters: time the lift with the jump — drive upward, not inward.\n3. Call system: code word = position of throw.\n4. 10 lineouts each side of the lineout. Focus on clean, fast ball.' },
      { title: 'Defensive Drift vs. Blitz Read', duration: '10 min', category: 'IQ & Strategy', intel: '1. Set your defensive line flat.\n2. "Drift" call: slide out one player wide to cover the edge.\n3. "Blitz" call: step up hard and fast to cut the play off at the line.\n4. Alternate calls 10 times each — react within 1 second of the call.' },
      { title: 'Speed & Agility — Outside Back', duration: '12 min', category: 'Conditioning', intel: '1. Set 4 cones in a square (5m sides).\n2. Sprint diagonal, shuffle lateral, backpedal, burst forward.\n3. 6 full rotations. Rest 40s.\n4. Replicates the multi-directional movement of wings and fullbacks.' },
    ],
    aiContext: 'Rugby Union: 80 minutes, two 40-minute halves. 15 players each side. Set pieces (scrums, lineouts) are critical technical elements. Forwards are power-based; backs need pace and agility. Open-side flanker and hooker have the highest work rates. Training should address both set-piece technique and open-play fitness. Upper body strength work should be periodized away from match weeks.',
  },

  Netball: {
    positions: ['Goal Shooter', 'Goal Attack', 'Wing Attack', 'Centre', 'Wing Defence', 'Goal Defence', 'Goal Keeper'],
    abilities: ['Footwork', 'Passing', 'Shooting', 'Defending', 'Communication', 'Agility'],
    improvements: ['Lead & Change', 'Court Sense', 'Intercept Timing', 'Rebounding', 'Feeding the Circle', 'Composure Under Pressure'],
    drills: [
      { title: 'Landing & Pivot Footwork', duration: '10 min', category: 'Skills', intel: '1. Catch the ball, land on two feet simultaneously (jump stop).\n2. Pivot on your landing foot — keep the other foot off the ground.\n3. Drive the pass out from the pivot — don\'t travel.\n4. 20 catches with pivot, alternating left and right landing foot.' },
      { title: 'Centre Pass Set Play', duration: '12 min', category: 'IQ & Strategy', intel: '1. Walk through your team\'s centre pass pattern (or a standard one: wing attack leads, goal attack drives).\n2. Centre player passes to the lead, then runs into support position.\n3. Sprint through the full pattern 10 times.\n4. Focus on timing — the pass and lead must coincide within 0.5 seconds.' },
      { title: 'Lead & Change Direction', duration: '10 min', category: 'Conditioning', intel: '1. Sprint toward a defender (cone), plant your outside foot, change direction hard.\n2. "V-cut": go one way, push off, sprint back the other way.\n3. 12 V-cuts, 30s rest between every 4.\n4. Builds the sharp direction change needed to lose a defender.' },
      { title: 'Shooting Arc — Follow-Through', duration: '12 min', category: 'Position Specific', intel: '1. Stand central, 3m from post.\n2. Hold follow-through — fingers pointing at the ring — for 2 seconds after each shot.\n3. Move back to 4m, then to the edge of the shooting circle.\n4. 10 shots each position. Track percentage.' },
      { title: 'Intercept Timing Drill', duration: '10 min', category: 'Position Specific', intel: '1. A feeder passes to a target 5m away.\n2. Position yourself between the two — time your movement to intercept.\n3. Don\'t go early. Wait until the ball leaves the feeder\'s hands.\n4. 15 intercept attempts. Realistic tempo — not "hand it to you."' },
      { title: 'Double Dodge', duration: '10 min', category: 'Skills', intel: '1. Take one step in a false direction, then sharply drive the other way.\n2. Call for the ball as soon as you\'re in space.\n3. Practice both left-then-right and right-then-left dodges.\n4. 10 each direction. Stay explosive — the dodge must be believable.' },
      { title: 'Feed into the Circle', duration: '12 min', category: 'Position Specific', intel: '1. Wing Attack / Centre role: position at the edge of the circle.\n2. Feed the ball to a shooter driving toward the post.\n3. The pass should be catchable while the shooter is moving — not flat.\n4. 15 feeds. Vary: lob pass, flat pass, bounce pass.' },
      { title: 'Zone Defence Hold', duration: '10 min', category: 'IQ & Strategy', intel: '1. Set up your zone area with cones.\n2. As the ball moves to your side, step forward and apply pressure.\n3. If the ball goes away, recover into your zone — don\'t ball-watch.\n4. Walk through 8 ball-movement scenarios, then jog through 6.' },
      { title: 'Transition Attack to Defence', duration: '12 min', category: 'Conditioning', intel: '1. Sprint to the offensive circle (attack).\n2. On a turnover signal, sprint back to the defensive zone (15m+ run).\n3. Arrive ready to defend — not exhausted.\n4. 8 full transition reps. Rest 40s between.' },
      { title: 'Rebounding Position — GK & GD', duration: '10 min', category: 'Position Specific', intel: '1. Shooter takes a shot. You must box out — step in front of the shooter before the ball hits the ring.\n2. Make contact with the back of the shooter, hands up for the ball.\n3. 10 rebound scenarios. If you get the ball, outlet quickly to your WD.' },
      { title: 'Reactive Agility — Ladder + Call', duration: '10 min', category: 'Conditioning', intel: '1. Run agility ladder (4 patterns).\n2. On each exit, a coach calls "left" or "right" — sprint that direction to a cone.\n3. Forces reactive decision-making — no anticipating.\n4. 6 full ladder runs with a directional call each time.' },
    ],
    aiContext: 'Netball: 4 x 15-minute quarters (Super Netball). High-intensity multi-directional sport. No running with the ball — all movement is about getting free, receiving, and re-delivering quickly. Centre has the highest work rate. GS/GA focus more on positioning and shooting. Footwork rules are strictly enforced. Training should emphasize agility, quick decision-making, and position-specific skills.',
  },

  Cricket: {
    positions: ['Opening Batter', 'Top-Order Batter', 'Middle-Order Batter', 'Lower-Order Batter', 'Wicket-Keeper', 'Pace Bowler', 'Swing Bowler', 'Spin Bowler', 'All-Rounder'],
    abilities: ['Timing', 'Placement', 'Bowling Action', 'Fielding', 'Concentration', 'Physical Fitness'],
    improvements: ['Playing Swing/Seam', 'Back-Foot Defence', 'Running Between Wickets', 'Spin Reading', 'Bowling Variation', 'Catching Under Pressure'],
    drills: [
      { title: 'Cover Drive — Soft Hands', duration: '12 min', category: 'Skills', intel: '1. Toss the ball to yourself (or use a tee).\n2. Drive through the off side — lead with your elbow, soft hands at impact.\n3. Watch the ball onto the bat face — delay the head turn.\n4. 20 drives, focus on the sound of the contact: a clean "thwack," not a scuff.' },
      { title: 'Front Foot Defence', duration: '10 min', category: 'Skills', intel: '1. Step forward — your front foot lands beside the pitch of the ball.\n2. Bat face angled slightly down — kill the ball, don\'t push.\n3. Head over the ball.\n4. 20 defences against a throw or toss. Any ball that goes forward is a mistake.' },
      { title: 'Fast Bowl Run-Up & Action', duration: '15 min', category: 'Position Specific', intel: '1. Walk your run-up — count your steps from mark to crease.\n2. At the crease: coil your body in the gather, front arm pulls high.\n3. Release point: over the top, not around the side.\n4. 20 deliveries at 70% pace, focusing on action not speed.' },
      { title: 'Spin Grip & Flight', duration: '10 min', category: 'Position Specific', intel: '1. Off-spin: fingers across the seam, flick through the delivery. Feel the revs, not the pace.\n2. Leg-spin: seam across, wrist behind ball at release.\n3. Bowl against a wall: 10 off-spin, 10 leg-spin.\n4. Count the revolutions on each delivery.' },
      { title: 'Catching Reaction Drill', duration: '10 min', category: 'Skills', intel: '1. Stand 5m from a wall or catcher.\n2. Ball thrown hard at different heights and angles — react and catch.\n3. Soft hands: fingers pointing up for chest-high balls, down for low balls.\n4. 30 catches. If you drop 3 in a row, slow the pace down.' },
      { title: 'Fielding — Ground Ball Dive', duration: '12 min', category: 'Skills', intel: '1. Ball hit or rolled to your left or right.\n2. Attack it — don\'t wait for it to come to you.\n3. Get low with your hands, field cleanly, hit the stumps in one motion.\n4. 8 dives each side. Full commitment — half-hearted dives lead to misfields.' },
      { title: 'Running Between Wickets — 2s & 3s', duration: '10 min', category: 'Conditioning', intel: '1. Sprint the full 22-yard pitch, turn with a dive or slide.\n2. Sprint back. This is one run.\n3. Do a "two": sprint, turn, sprint, turn — all at full pace.\n4. 10 singles, 8 twos, 4 threes. Time each — your batting partner should never be out of breath while you run hard.' },
      { title: 'Playing Swing — Head Still', duration: '12 min', category: 'Skills', intel: '1. Have a partner bowl or throw with a swinging action.\n2. Watch the ball LATE — resist playing early.\n3. If it swings away: leave or drive through cover.\n4. If it swings in: work to leg or defend on the back foot.\n5. 20 balls — call your shot type before each delivery.' },
      { title: 'Wicket-Keeping — Stance & Glove Work', duration: '12 min', category: 'Position Specific', intel: '1. Set up in a low stance — fingertips on the ground, weight forward.\n2. Receive 20 balls at varying heights: chest, shins, wide.\n3. Move sideways with the feet first, then the gloves.\n4. Against spin: take up and across your body, not across your body first.' },
      { title: 'Bowling Control — Line & Length', duration: '15 min', category: 'Skills', intel: '1. Mark a target: a good length spot is 6–7m from the stumps.\n2. Bowl 20 deliveries aiming at the target.\n3. A "hit" = landed within 0.5m of target on the off-stump line.\n4. Track: hits vs. total. Target 12/20.' },
      { title: 'Back-Foot Drive', duration: '10 min', category: 'Skills', intel: '1. Ball dropped short — weight rocks back onto the back foot.\n2. Drive through the off side — but keep the weight back throughout.\n3. The common error: stepping into a short ball. Stay back.\n4. 15 back-foot drives from throws or a short-ball feed.' },
    ],
    aiContext: 'Cricket: Test (5 days), One-Day (50 overs), T20 (20 overs) formats require different fitness profiles. Batting requires concentration and burst intensity; bowling requires aerobic endurance and explosive repeated action; fielding requires speed and agility. Training should match the format being played. Bowlers need arm care — monitor bowling loads carefully. Game day nutrition depends on position: batters need sustained energy, bowlers need to be sharp from ball 1.',
  },

  Tennis: {
    positions: ['Baseline Player', 'Serve & Volleyer', 'All-Court Player', 'Doubles Specialist'],
    abilities: ['Footwork', 'Serve', 'Forehand', 'Backhand', 'Mental Toughness', 'Reaction Speed'],
    improvements: ['Net Play', 'Second Serve', 'Drop Shot', 'Slice', 'Physicality', 'Return of Serve'],
    drills: [
      { title: 'Cross-Court Forehand — Consistency', duration: '12 min', category: 'Skills', intel: '1. Stand on the baseline, deuce side.\n2. Rally cross-court forehand — the goal is 20 consecutive balls in the court.\n3. Rotate hips into the shot. Finish high and out of the court.\n4. Reset to zero if you miss. Record your best run.' },
      { title: 'Serve — Toss & Contact Point', duration: '12 min', category: 'Skills', intel: '1. Practice the ball toss in isolation: arm straight, release at the top.\n2. The toss should land on your strings if you let it drop.\n3. Contact at full arm extension, slightly in front of your head.\n4. 30 serves: 15 deuce, 15 ad. Record first-serve percentage.' },
      { title: 'Side-to-Side Footwork', duration: '10 min', category: 'Conditioning', intel: '1. Stand at the centre mark.\n2. Sprint to the doubles alley, recover to centre, sprint to the other alley.\n3. Use split-step timing: hit the imaginary ball, split step, go.\n4. 10 full width movements. Rest 30s.' },
      { title: 'Topspin Backhand — Loop Swing', duration: '12 min', category: 'Skills', intel: '1. Drop the racquet head low (below the ball).\n2. Swing up and across — finish over the left shoulder (for right-handed players).\n3. The brushing motion creates topspin — not a flat hit.\n4. 30 backhands against a wall or with a ball machine.' },
      { title: 'Overhead Smash', duration: '10 min', category: 'Skills', intel: '1. Position yourself behind the ball — it should be slightly in front of your racquet shoulder.\n2. Coil like a serve: turn your shoulder, continental grip.\n3. Strike flat at the top, into the court not the fence.\n4. 20 overheads from a partner lob (or self-toss).' },
      { title: 'Return of Serve — Split Step', duration: '10 min', category: 'Skills', intel: '1. As the server tosses the ball, do your split step — land just before contact.\n2. React to the direction: take a unit turn immediately.\n3. Take short backswing on fast serves — use their pace.\n4. 20 returns each side. Focus on the split step first, placement second.' },
      { title: 'Drop Shot & Lob Combo', duration: '10 min', category: 'IQ & Strategy', intel: '1. Approach the net, hit a drop shot (slow, backspin, lands short).\n2. If opponent gets there, retreat and lob over them.\n3. Practice the drop shot technique: open racquet face, slice under the ball.\n4. 15 drop shots, 10 offensive lobs.' },
      { title: 'Approach Shot Patterns', duration: '12 min', category: 'IQ & Strategy', intel: '1. Short ball in the court — attack it.\n2. Move through the ball (don\'t stop), hit down the line, follow in to net.\n3. Options at net: volley the setup, or put away the poach.\n4. Walk through 10 approach scenarios: cross-court short ball, mid-court ball.' },
      { title: 'First Serve Pressure — 50%+ Pace', duration: '12 min', category: 'Skills', intel: '1. Serve 20 first serves at 70% of your max pace.\n2. Target: T, Body, Wide. Call your target before each serve.\n3. Hit target = point. Miss net or long = negative.\n4. Track percentage in + placement hits. Prioritize control before speed.' },
      { title: 'Recovery Split Step', duration: '10 min', category: 'Conditioning', intel: '1. After every imaginary shot, recover to the centre mark.\n2. As you arrive, do a split step — land just as the opponent "hits."\n3. 20 recovery sequences at match tempo.\n4. Never let your feet go flat between shots.' },
      { title: 'Slice Backhand — Stay Low', duration: '10 min', category: 'Skills', intel: '1. Take the racquet back at shoulder height, continental grip.\n2. Swing down and through — cut under the ball.\n3. Finish low, racquet below the net level.\n4. 20 slices. Use it on approach shots and to neutralize heavy topspin.' },
    ],
    aiContext: 'Tennis: Match length varies — 60 minutes to 4+ hours. High-intensity rallies interspersed with rest between points. Aerobic base is crucial for long matches. Explosive footwork and upper-body rotation are key. Singles requires covering the full court; doubles is about positioning and poaching. Mental focus is as important as physical fitness — include visualization in training blocks.',
  },

  Swimming: {
    positions: ['Freestyle (Sprint)', 'Freestyle (Distance)', 'Backstroke', 'Breaststroke', 'Butterfly', 'Individual Medley', 'Open Water'],
    abilities: ['Technique', 'Starts & Turns', 'Breathing Control', 'Pace Awareness', 'Endurance', 'Explosive Power'],
    improvements: ['Underwater Dolphin Kick', 'Stroke Efficiency', 'Race Pace Fitness', 'Bilateral Breathing', 'Turn Speed', 'Stroke Rate'],
    drills: [
      { title: 'Catch-Up Drill — Freestyle', duration: '10 min', category: 'Skills', intel: '1. One arm leads the pull while the other remains extended at the front.\n2. Only begin pulling when your recovering arm "catches up" to the leading hand.\n3. Swim 4 x 50m focusing on high elbow catch entry.\n4. Forces proper timing — no crossing over the midline.' },
      { title: 'Bilateral Breathing Sets', duration: '12 min', category: 'Skills', intel: '1. Breathe every 3 strokes (alternate sides).\n2. 4 x 100m. First 2 lengths: breathe only right. Next 2: only left.\n3. A forced bilateral pattern trains both sides equally.\n4. Stay relaxed — don\'t gasp. Head rotation, not lifting.' },
      { title: 'Kick Set with Board', duration: '15 min', category: 'Conditioning', intel: '1. Hold a kickboard, extend arms straight.\n2. 6 x 50m kick-only: flutter kick (freestyle/backstroke) or dolphin kick (butterfly/turns).\n3. Count your kicks per length — consistency matters more than speed.\n4. Rest 20s between each 50.' },
      { title: 'Underwater Dolphin Kick', duration: '10 min', category: 'Skills', intel: '1. Push off the wall in streamline (arms locked over ears, hands stacked).\n2. Kick from hips, not knees. The power comes from the hip flexors.\n3. Stay underwater as long as comfortable — don\'t sacrifice technique for time.\n4. 10 wall push-off dolphin kick efforts. Aim for 15m underwater.' },
      { title: 'Flip Turn Technique', duration: '12 min', category: 'Skills', intel: '1. Approach wall at normal speed.\n2. Begin the somersault 1 arm-length from the wall. Tuck tight.\n3. Feet hit the wall — push off in streamline, 1/4 roll to face down.\n4. 10 flip turns per end: 5 fast, 5 slow (slow = technique focus).' },
      { title: 'Pull Buoy Isolation', duration: '12 min', category: 'Skills', intel: '1. Place pull buoy between thighs (no leg kick).\n2. Focus entirely on arm pull mechanics: high elbow, S-pull pattern, push past hip.\n3. 4 x 100m.\n4. Feel where your pull is weakest — beginning, middle, or finish.' },
      { title: 'Sprint Set — 10 x 25m', duration: '12 min', category: 'Conditioning', intel: '1. All-out sprint each 25m.\n2. Rest 30s between each.\n3. Stroke count: aim for same number of strokes in rep 10 as rep 1.\n4. Any stroke. Power + efficiency must remain constant under fatigue.' },
      { title: 'Sculling Drill', duration: '10 min', category: 'Skills', intel: '1. Lie on your back or front, arms extended forward.\n2. Scull with wrists and forearms — figure-8 motion — to move forward.\n3. This builds feel for the water (proprioception) and forearm paddle pressure.\n4. 2 x 50m sculling.' },
      { title: 'Threshold Pace Sets', duration: '20 min', category: 'Conditioning', intel: '1. Find your 1500m average pace per 100m.\n2. Swim 6 x 200m at exactly that pace. Use the clock — not feel.\n3. Rest 30s between each 200.\n4. This is your aerobic threshold — the engine that powers all race distances.' },
      { title: 'Start Drill — Block Reaction', duration: '10 min', category: 'Skills', intel: '1. Set up in starting position.\n2. On the start signal (or a clap), react and enter the water with body in a straight line.\n3. Measure reaction time to surface or first stroke.\n4. 8 start reps. Each one should be maximum effort — starts can win or lose races.' },
      { title: 'Stroke Count Awareness', duration: '12 min', category: 'IQ & Strategy', intel: '1. Swim 4 x 50m. Count every stroke cycle.\n2. Target: reduce your count per length by 2 over the set (more efficient glide).\n3. Then add speed without increasing the count.\n4. Stroke count + speed = efficiency rating.' },
    ],
    aiContext: 'Swimming: Races from 50m (26 seconds) to 1500m/10km open water. Training cycles through technique, aerobic base, speed work, and taper. The sport is technique-heavy — even elite swimmers spend 30%+ of training on drills. Shoulder health is critical (high injury area). Training volume is measured in kilometres; competitive swimmers do 6–12km per session. Taper 1 week before major meets.',
  },

  Athletics: {
    positions: ['Sprinter (100/200m)', 'Quarter-Miler (400m)', 'Middle Distance (800/1500m)', 'Long Distance (5000m+)', 'Hurdler', 'Long Jumper', 'High Jumper', 'Triple Jumper', 'Shot Put / Discus', 'Javelin', 'Hammer', 'Decathlete'],
    abilities: ['Explosive Power', 'Stride Efficiency', 'Endurance', 'Jumping Technique', 'Throwing Mechanics', 'Mental Toughness'],
    improvements: ['Block Start', 'Race Tactics', 'Strength', 'Speed Endurance', 'Takeoff Technique', 'Rotation/Release'],
    drills: [
      { title: 'Drive Phase — Block Work', duration: '12 min', category: 'Skills', intel: '1. Set blocks: front foot 1.5 shoe-lengths from line, back foot 2.5.\n2. "Set" position: hips above shoulders, 90° front knee angle.\n3. Drive for 10m only — focus on staying low, not upright.\n4. 8 block starts. Stay in drive phase until 30m naturally.' },
      { title: 'High Knee / A-Skip', duration: '10 min', category: 'Skills', intel: '1. Skip forward, driving the knee up to hip height rhythmically.\n2. Foot should dorsiflex (toes up) on every contact.\n3. Arms drive in opposition — vigorous, not floppy.\n4. 4 x 30m A-skips. Then 4 x 30m B-skips (extend the leg forward from the high knee).' },
      { title: 'Wicket Runs — Stride Length', duration: '12 min', category: 'Skills', intel: '1. Set cones/marks at your natural stride length apart (roughly 1.8m for juniors).\n2. Sprint through the wickets without chopping your stride.\n3. Each rep, try to extend your stride by 5cm without reaching.\n4. 6 x 40m wicket runs. Film if possible.' },
      { title: 'Long Easy Run', duration: '30 min', category: 'Conditioning', intel: '1. Run at conversational pace — you must be able to speak full sentences.\n2. Distance runners: 5–8km. Sprinters: 20–25 min jog max.\n3. This builds aerobic base and aids recovery.\n4. No headphones if running roads. Keep form: upright, relaxed arms, midfoot strike.' },
      { title: 'Tempo Intervals — 6 x 300m', duration: '25 min', category: 'Conditioning', intel: '1. Run 300m at your 400m race pace (roughly 85-90% effort).\n2. Walk 200m between each (2–3 min recovery).\n3. 6 reps total.\n4. The 6th should feel hard but controlled — if you can\'t hold pace, drop to 5 reps.' },
      { title: 'Bounding Series', duration: '12 min', category: 'Strength', intel: '1. Single-leg bounding: push off one leg, land on the other, alternate.\n2. Double-leg bounds: both feet at once, maximum horizontal distance.\n3. Power hops: one leg, 8 hops for distance, then switch.\n4. 4 sets of 20m each. Rest fully between sets — this is power, not endurance.' },
      { title: 'Takeoff Drills — Long/High Jump', duration: '12 min', category: 'Position Specific', intel: '1. Mark your takeoff point.\n2. Run 4 strides and hit the board — plant your foot flat, not heel.\n3. Drive your knee and arms upward on takeoff.\n4. 8 practice takeoffs. Film from the side: your takeoff should be a single powerful contact, not a slowing step.' },
      { title: 'Standing Shot Put Rotation', duration: '10 min', category: 'Position Specific', intel: '1. Stand at the toe board, shot against neck.\n2. Rotate from hips → shoulders → arm → wrist in sequence.\n3. Release at 45° — fingers behind and under the implement.\n4. 15 throws. Power comes from legs and rotation — not the arm.' },
      { title: 'Plyometric Box Jumps', duration: '12 min', category: 'Strength', intel: '1. Stand in front of a box (40–60cm).\n2. Drop to a quarter squat, then explode onto the box — both feet land simultaneously.\n3. Step down, never jump down.\n4. 4 sets of 6 reps. Rest 90s. Full power on every rep — quality over quantity.' },
      { title: 'Race Tactics Visualization', duration: '8 min', category: 'IQ & Strategy', intel: '1. Sit in a quiet space. Close your eyes.\n2. Visualize your entire race from command to finish line.\n3. Include: start, first 100m feeling, midrace position, final drive.\n4. If a negative thought enters, replace it with a specific technique cue.\n5. Do this before every race and training session.' },
      { title: 'Hurdle Trail Leg Drill', duration: '10 min', category: 'Skills', intel: '1. Walk beside a hurdle. Practice the trail leg: hip opens out, knee snaps through high.\n2. The trail leg should not drag — it must snap through at hip height.\n3. Then walk + trail leg rhythm: 3 steps between each hurdle.\n4. 20 hurdles at walking speed, 10 at jogging speed.' },
    ],
    aiContext: 'Athletics (Track & Field): Event-specific demands vary enormously. Sprinters (100–400m) need explosive power and anaerobic conditioning. Distance runners need aerobic base and race tactics. Jumpers and throwers need strength, power, and technical precision. Training is heavily periodized: build phase (volume), sharpening (speed), and taper (before competition). Athletes must manage training loads carefully — overtraining is the most common injury cause.',
  },

  'American Football': {
    positions: ['Quarterback', 'Running Back', 'Wide Receiver', 'Tight End', 'Offensive Lineman', 'Linebacker', 'Cornerback', 'Safety', 'Defensive Lineman'],
    abilities: ['Strength', 'Power', 'Speed', 'Route Running', 'Catching', 'Blocking'],
    improvements: ['Explosiveness', 'Vision', 'Technique', 'Flexibility', 'Endurance', 'Football IQ'],
    drills: [
      { title: 'Route Running — Crisp Breaks', duration: '12 min', category: 'Position Specific', intel: '1. Jog 5 yards at 60%, then plant and cut at full speed.\n2. Cuts: in, out, dig, post, corner. Each one must be sudden.\n3. Plant foot lands at the stem of the route — not before.\n4. 8 reps each route type. Clean separation comes from the plant, not the speed.' },
      { title: 'Explosive Start — 3-Point Stance', duration: '10 min', category: 'Conditioning', intel: '1. Set your stance: weight forward, 3-point contact, flat back.\n2. On the snap signal (clap), drive off the line — arms explode, legs drive simultaneously.\n3. First 3 steps are key — don\'t rise upright until step 4.\n4. 10 start reps. Record your 10-yard time.' },
      { title: 'Hand Fighting — Pass Rush', duration: '12 min', category: 'Skills', intel: '1. Pair with a partner or use a bag as the blocker.\n2. Practice: rip move (arm under), swim move (over), push-pull.\n3. Each move starts with a punch — establish the initial contact before the move.\n4. 5 reps each move each side. Speed and leverage beat size.' },
      { title: 'QB Footwork — Dropback Mechanics', duration: '10 min', category: 'Position Specific', intel: '1. 3-step drop: quick, rhythmic. Last step is a hitch step before throwing.\n2. 5-step drop: generate momentum, gather on step 5.\n3. Eyes downfield throughout — feet work independently of your read.\n4. 10 reps each drop. Practice the throw motion at the end of each.' },
      { title: 'Change of Direction — Cone Drill', duration: '10 min', category: 'Conditioning', intel: '1. Set 3 cones in a straight line, 5 yards apart.\n2. Sprint to the first, back to start, sprint to the second, back, sprint to the third.\n3. Rest 45s. 6 full reps.\n4. Plant foot, not the heel. Stay low on the turns.' },
      { title: 'Ball Security — High & Tight', duration: '8 min', category: 'Skills', intel: '1. Hold the ball high and tight: elbow locked to ribs, fingertips over the point, bicep covers the front.\n2. Have someone try to swipe the ball 10 times — it should not come out.\n3. Switch hands: left arm high and tight, same test.\n4. If the ball comes out, you\'re not tucked right.' },
      { title: 'Linebacker Run Fit', duration: '10 min', category: 'Position Specific', intel: '1. Identify your gap (A, B, or C gap based on the play).\n2. Step into the gap with your inside foot first — square your hips.\n3. Fit the tackle: chest on chest, facemask to the ballcarrier\'s numbers.\n4. Practice 8 gap fits versus a bag or partner at 60% speed.' },
      { title: 'Catching — Concentration Balls', duration: '10 min', category: 'Skills', intel: '1. Look the ball all the way into your hands — not body catch.\n2. Catch 20 balls at varying heights with a partner or against a wall.\n3. Catch with your hands, not your pads. Thumbs in for high balls, thumbs out for low.\n4. The last step before the catch is a "gather step" — don\'t leap.' },
      { title: 'Plyometric Power — Box Jump Series', duration: '12 min', category: 'Strength', intel: '1. Broad jump (horizontal): maximize distance, soft landing.\n2. Box jump (vertical): drive arms and knees upward, land quiet.\n3. Single-leg jump: left and right, 5 each.\n4. 3 rounds. Rest 90s between. Full effort every rep.' },
      { title: 'Film Study Simulation', duration: '10 min', category: 'IQ & Strategy', intel: '1. Watch 5 minutes of film of your own position (YouTube or team film).\n2. Identify: pre-snap read, first 2 steps, decision, result.\n3. Pause at decision moments — what would you do?\n4. Knowledge of the game is the highest-leverage skill a young athlete can develop.' },
    ],
    aiContext: 'American Football: 4 x 15-minute quarters (NFL), 60-minute games. Offense and defense rotate — most players are on the field for half the game. Each play is a maximum-intensity burst (3–8 seconds) followed by a 30-40 second huddle. Strength, power, and explosion are the primary physical demands. Linemen are the heaviest; skill positions (WR, CB, RB) need elite speed. Summer conditioning and pre-season are critical for injury prevention.',
  },
};

export const SPORT_NAMES = Object.keys(SPORTS_CONFIG);

export function getSportConfig(sport: string): SportConfig {
  return SPORTS_CONFIG[sport] || SPORTS_CONFIG['Soccer'];
}

// Seeded shuffle — same order for the same date, different each day
export function getDailyDrills(sport: string, count = 8): DrillTemplate[] {
  const config = getSportConfig(sport);
  const drills = [...config.drills];
  const seed = parseInt(new Date().toLocaleDateString('en-CA', { timeZone: 'Australia/Sydney' }).replace(/-/g, ''), 10);
  // Simple seeded Fisher-Yates
  let s = seed;
  for (let i = drills.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [drills[i], drills[j]] = [drills[j], drills[i]];
  }
  return drills.slice(0, Math.min(count, drills.length));
}
